# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/aka/configuration.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("lib/aka/configuration.proto", :syntax => :proto2) do
    add_message "Configuration" do
      required :version, :string, 1
      repeated :shortcuts, :message, 2, "Configuration.Shortcut"
      repeated :links, :message, 3, "Configuration.Link"
    end
    add_message "Configuration.Shortcut" do
      required :shortcut, :string, 1
      required :command, :string, 2
      repeated :tag, :string, 3
      optional :description, :string, 4
      optional :function, :bool, 5
    end
    add_message "Configuration.Link" do
      repeated :tag, :string, 1
      required :output, :string, 2
    end
  end
end

Configuration = Google::Protobuf::DescriptorPool.generated_pool.lookup("Configuration").msgclass
Configuration::Shortcut = Google::Protobuf::DescriptorPool.generated_pool.lookup("Configuration.Shortcut").msgclass
Configuration::Link = Google::Protobuf::DescriptorPool.generated_pool.lookup("Configuration.Link").msgclass
